(function(){
'use strict';
var works=[{"id": "archive", "title": "有档可查", "en": "CREATIVE ARCHIVE", "type": "AI 产品视觉", "x": 11, "y": 30, "rotate": -15}, {"id": "pet-city", "title": "宠物城市正式开城", "en": "PET CITY", "type": "品牌创意海报", "x": 25, "y": 16, "rotate": -9}, {"id": "red-hood", "title": "童话剧场", "en": "RED HOOD", "type": "AI 叙事场景", "x": 41, "y": 11, "rotate": 2}, {"id": "high-speed", "title": "士气别想逃", "en": "HIGH-SPEED PURSUIT", "type": "汽车视觉海报", "x": 58, "y": 13, "rotate": 8}, {"id": "luno-poster", "title": "Luno · 向光而行", "en": "UNDER THE SUN", "type": "角色视觉海报", "x": 74, "y": 20, "rotate": 13}, {"id": "luno-scene", "title": "Luno · 木屋奇遇", "en": "A LITTLE COURAGE", "type": "角色场景设计", "x": 88, "y": 35, "rotate": 16}, {"id": "demo-pose", "title": "DEMO · 动态研究", "en": "CHARACTER POSE", "type": "三维角色探索", "x": 11, "y": 70, "rotate": 14}, {"id": "character", "title": "角色 · 灵感瞬间", "en": "CHARACTER STUDY", "type": "AI 角色设计", "x": 26, "y": 84, "rotate": 8}, {"id": "luno-study", "title": "Luno · 角色探索", "en": "LUNO EXPLORATION", "type": "IP 视觉探索", "x": 43, "y": 88, "rotate": -2}, {"id": "buddy-poster", "title": "一起待一会儿", "en": "BUDDY POINT", "type": "插画品牌视觉", "x": 60, "y": 86, "rotate": -8}, {"id": "legal-slacking", "title": "合法摆烂计划", "en": "LEGAL SLACKING PLAN", "type": "创意 KV 海报", "x": 76, "y": 81, "rotate": -13}, {"id": "desert-band", "title": "沙漠乐队", "en": "DESERT BAND", "type": "AI 场景视觉", "x": 89, "y": 66, "rotate": -17}, {"id": "buddy-wide", "title": "一起待一会儿", "en": "BUDDY POINT", "type": "插画 · 品牌视觉", "description": "把轻松的相聚时刻，变成一眼就能感受到的品牌情绪。"}, {"id": "dominos", "title": "一间充满想象的披萨店", "en": "A LITTLE WORLD OF PIZZA", "type": "AI 场景 · 创意视觉", "description": "用微缩场景、角色与光影，建立具有故事感的产品世界。"}, {"id": "beat-beast", "title": "节拍声兽", "en": "BEAT BEAST", "type": "产品概念 · 视觉海报", "description": "让声音拥有性格，让产品成为画面的主角。"}];
var dialog=document.querySelector('.lightbox'),current=0,trigger=null;
var title=dialog.querySelector('#lightbox-title'),photo=dialog.querySelector('.lightbox-image img'),meta=dialog.querySelector('.lightbox-top .eyebrow');
function show(index){current=(index+works.length)%works.length;var work=works[current];title.textContent=work.title;photo.src='assets/'+work.id+'.webp';photo.alt=work.title+'完整作品';meta.textContent=(current+1)+' / '+works.length+' — '+work.type;}
function close(){dialog.close();document.body.style.overflow='';if(trigger)trigger.focus({preventScroll:true});}
document.querySelectorAll('[data-work]').forEach(function(link){link.addEventListener('click',function(event){if(typeof dialog.showModal!=='function')return;event.preventDefault();trigger=link;show(Number(link.dataset.work));dialog.showModal();document.body.style.overflow='hidden';});});
dialog.querySelector('.close-button').addEventListener('click',close);
dialog.querySelector('[data-prev]').addEventListener('click',function(){show(current-1);});
dialog.querySelector('[data-next]').addEventListener('click',function(){show(current+1);});
dialog.addEventListener('cancel',function(e){e.preventDefault();close();});
dialog.addEventListener('click',function(e){if(e.target===dialog)close();});
dialog.addEventListener('keydown',function(e){if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}if(e.key==='ArrowRight'){e.preventDefault();show(current+1);}});
var video=document.querySelector('.hero-art video'),toggle=document.querySelector('.motion-toggle');
function updateVideo(){var playing=!video.paused;toggle.setAttribute('aria-label',playing?'暂停背景动态':'播放背景动态');toggle.children[0].textContent=playing?'Ⅱ':'▷';toggle.children[1].textContent=playing?'暂停动态':'播放动态';}
video.muted=true;video.addEventListener('play',updateVideo);video.addEventListener('pause',updateVideo);
var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){var play=video.play();if(play&&play.catch)play.catch(function(){});}
toggle.addEventListener('click',function(){if(video.paused){var p=video.play();if(p&&p.catch)p.catch(function(){});}else video.pause();});
var copy=document.querySelector('.copy-button');copy.addEventListener('click',function(){var email='Zhangmt0625@outlook.com';function done(){copy.textContent='邮箱已复制 ✓';setTimeout(function(){copy.textContent='复制邮箱';},2000);}function fallback(){var text=document.createElement('textarea');text.value=email;text.style.position='fixed';text.style.opacity='0';document.body.appendChild(text);text.select();var ok=false;try{ok=document.execCommand('copy');}catch(e){}text.remove();if(ok)done();else{copy.textContent='请选中上方邮箱复制';}}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(email).then(done,fallback);else fallback();});
if('IntersectionObserver' in window){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){var id=entry.target.id==='selected'?'work':entry.target.id;document.querySelectorAll('.site-header nav a').forEach(function(a){var active=a.getAttribute('href')==='#'+id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}});},{rootMargin:'-20% 0px -55% 0px'});document.querySelectorAll('main > section[id],footer[id]').forEach(function(section){observer.observe(section);});}
var caseCss=document.createElement('link');caseCss.rel='stylesheet';caseCss.href='case-studies.css?v=6';document.head.appendChild(caseCss);
var caseScript=document.createElement('script');caseScript.src='case-studies.js?v=8';document.body.appendChild(caseScript);
var heroFit=document.createElement('style');heroFit.textContent='.hero-art video{object-fit:cover!important;object-position:56% center!important}';document.head.appendChild(heroFit);
})();
